clean:
	rm -rf *.exe *.dSYM *~

5.1: 5.1.cpp
	g++ -Wall -DDEBUG -g -std=c++11 5.1.cpp -o 5.1.exe

5.2: 5.2.cpp
	g++ -Wall -DDEBUG -g -std=c++11 5.2.cpp -o 5.2.exe

test: test.cpp
	g++ -Wall -DDEBUG -g -std=c++11 test.cpp -o test.exe
